version: "3"
networks:
  url_shortener:
    driver: bridge
services:
 url_shortener:
  command: ["rails","server","-b","0.0.0.0","-p","3000"]
  build:
      context: .
      dockerfile: docker/url_shortener.dockerfile
  container_name: url_shortener
  volumes:
       - .:/app
  environment:
       - RAILS_ENV=development
  networks:
    url_shortener:
      aliases:
          - url_shortener
  ports:
    - 3000:3000

 postgres:
    build:
      context: .
      dockerfile: docker/postgres.dockerfile
    container_name: url_shortener_postgres
    environment:
      POSTGRES_DB: url_shortener_development
      POSTGRES_USER: vlad_psql
      POSTGRES_PASSWORD: vlad_psql
    networks:
      url_shortener:
        aliases:
          - postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
